# Generated by Django 5.2.4 on 2025-07-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='guests/'),
        ),
    ]
